### ISSUE TITLE
Error in running example scripts

### ISSUE THREAD

**Issue by kadenmarika** [si-cim/prototorch_models#3]
Running: glvq_iris.py or glvq_mnist.py the following error appears:

TypeError: `initializer` has to be some kind of `ComponentsInitializer`. You provided: initializer='stratified_mean' instead.

**Comment by EAR-Development** [comment]
This problem is based on changes on the Prototorch package.

All Examples need to be changed.

**Comment by EAR-Development** [comment]
The commit 1c3613019b6a04f3613de94c5bef187e99d7e26f on dev branch should at least fix the iris example.

**Comment by theblackfly** [comment]
Thanks @EAR-Development for updating the example scripts. With that, I'm closing this issue.

**Comment by EAR-Development** [comment]
It is still open to update MNIST visualization callbacks.

**Comment by theblackfly** [comment]
@EAR-Development Are you fixing the visualization callback?

**Comment by theblackfly** [comment]
> It is still open to update MNIST visualization callbacks.

It should now be fixed. Closing this issue with that.
