### ISSUE TITLE
Error when using the GPU

### ISSUE THREAD

**Issue by dmoebius-dm** [si-cim/prototorch_models#8]
When running the glvq_iris.py example with gpus=1 in Trainer arguments the following error occurs:

 `  File "/home/ifm/dmoebius/KIML/python/prototorch/prototorch/functions/losses.py", line 8, in _get_matcher
    matcher = torch.eq(targets.unsqueeze(dim=1), labels)`
`RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!`

ScientificLinux 7.9
Python 3.8.8
Pytorch 1.8.1.

[glvqiris_gpu_error.txt](https://github.com/si-cim/prototorch_models/files/6467109/glvqiris_gpu_error.txt)

**Comment by EAR-Development** [comment]
Fixed in https://github.com/si-cim/prototorch_models/commit/0eac2ce32653dda7c22188263bbd06fe2bb287da.
